"""Add ai_summary field to Note

Revision ID: 4e7ce96d346e
Revises: a97e0fc077b5
Create Date: 2026-07-18 20:11:14.485936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7ce96d346e'
down_revision = 'a97e0fc077b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
