"""Add Attachment model for file uploads

Revision ID: a97e0fc077b5
Revises: f63b69986973
Create Date: 2026-07-18 19:16:08.936329

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a97e0fc077b5"
down_revision = "f63b69986973"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"], ["notes.id"], name=op.f("fk_attachments_note_id_notes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attachments")
    # ### end Alembic commands ###
